<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\Admin\\BlogController:index' => function () {
    return ($this->privates['service_locator.6bwwuNV'] ?? $this->load(__DIR__.'/getServiceLocator_6bwwuNVService.php'));
}, 'App\\Controller\\BlogController:commentNew' => function () {
    return ($this->privates['service_locator.zayYvVG'] ?? $this->load(__DIR__.'/getServiceLocator_ZayYvVGService.php'));
}, 'App\\Controller\\BlogController:index' => function () {
    return ($this->privates['service_locator.rIerrUe'] ?? $this->load(__DIR__.'/getServiceLocator_RIerrUeService.php'));
}, 'App\\Controller\\BlogController:search' => function () {
    return ($this->privates['service_locator.ppL.RmJ'] ?? $this->load(__DIR__.'/getServiceLocator_PpL_RmJService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.Syn2D.o'] ?? $this->load(__DIR__.'/getServiceLocator_Syn2D_OService.php'));
}, 'App\\Controller\\Admin\\BlogController::index' => function () {
    return ($this->privates['service_locator.6bwwuNV'] ?? $this->load(__DIR__.'/getServiceLocator_6bwwuNVService.php'));
}, 'App\\Controller\\BlogController::commentNew' => function () {
    return ($this->privates['service_locator.zayYvVG'] ?? $this->load(__DIR__.'/getServiceLocator_ZayYvVGService.php'));
}, 'App\\Controller\\BlogController::index' => function () {
    return ($this->privates['service_locator.rIerrUe'] ?? $this->load(__DIR__.'/getServiceLocator_RIerrUeService.php'));
}, 'App\\Controller\\BlogController::search' => function () {
    return ($this->privates['service_locator.ppL.RmJ'] ?? $this->load(__DIR__.'/getServiceLocator_PpL_RmJService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.Syn2D.o'] ?? $this->load(__DIR__.'/getServiceLocator_Syn2D_OService.php'));
})));
