<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Type\DateTimePickerType' shared autowired service.

require_once $this->targetDirs[3].'/src/Utils/MomentFormatConverter.php';
require_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
require_once $this->targetDirs[3].'/src/Form/Type/DateTimePickerType.php';

return $this->privates['App\Form\Type\DateTimePickerType'] = new \App\Form\Type\DateTimePickerType(new \App\Utils\MomentFormatConverter());
