<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.type_extension.upload.validator' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
require_once $this->targetDirs[3].'/vendor/symfony/form/Extension/Validator/Type/UploadValidatorExtension.php';

return $this->privates['form.type_extension.upload.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\UploadValidatorExtension(($this->services['translator'] ?? $this->getTranslatorService()), 'validators');
