<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.factory' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/form/FormFactoryInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/form/FormFactory.php';

return $this->services['form.factory'] = new \Symfony\Component\Form\FormFactory(($this->privates['form.registry'] ?? $this->load(__DIR__.'/getForm_RegistryService.php')), ($this->privates['form.resolved_type_factory'] ?? $this->load(__DIR__.'/getForm_ResolvedTypeFactoryService.php')));
