<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\PostVoter' shared autowired service.

require_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/VoterInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/Voter.php';
require_once $this->targetDirs[3].'/src/Security/PostVoter.php';

return $this->privates['App\Security\PostVoter'] = new \App\Security\PostVoter();
