<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcher.php';
require_once $this->targetDirs[3].'/vendor/symfony/security/Http/AccessMapInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/security/Http/AccessMap.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/(en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN)/admin'), array(0 => 'ROLE_ADMIN'), NULL);

return $instance;
