<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerSLb2Vfj\srcDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerSLb2Vfj/srcDevDebugProjectContainer.php';
}

if (!class_exists(srcDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerSLb2Vfj\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSLb2Vfj\srcDevDebugProjectContainer();
