<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerXboCub0\srcDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerXboCub0/srcDevDebugProjectContainer.php';
}

if (!class_exists(srcDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerXboCub0\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXboCub0\srcDevDebugProjectContainer();
