<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Admin\BlogController' shared autowired service.

require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
require_once $this->targetDirs[3].'/src/Controller/Admin/BlogController.php';

$this->services['App\Controller\Admin\BlogController'] = $instance = new \App\Controller\Admin\BlogController();

$instance->setContainer(($this->privates['service_locator.aqxUcvZ'] ?? $this->load(__DIR__.'/getServiceLocator_AqxUcvZService.php')));

return $instance;
