<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.translation_update' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/DumperInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/FileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/PhpFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/XliffFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/PoFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/MoFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/YamlFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/QtFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/CsvFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/IniFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/JsonFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/IcuResFileDumper.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Writer/TranslationWriterInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/translation/Writer/TranslationWriter.php';
require_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/TranslationUpdateCommand.php';

$a = new \Symfony\Component\Translation\Writer\TranslationWriter();
$a->addDumper('php', new \Symfony\Component\Translation\Dumper\PhpFileDumper());
$a->addDumper('xlf', new \Symfony\Component\Translation\Dumper\XliffFileDumper());
$a->addDumper('po', new \Symfony\Component\Translation\Dumper\PoFileDumper());
$a->addDumper('mo', new \Symfony\Component\Translation\Dumper\MoFileDumper());
$a->addDumper('yml', new \Symfony\Component\Translation\Dumper\YamlFileDumper());
$a->addDumper('yaml', new \Symfony\Component\Translation\Dumper\YamlFileDumper('yaml'));
$a->addDumper('ts', new \Symfony\Component\Translation\Dumper\QtFileDumper());
$a->addDumper('csv', new \Symfony\Component\Translation\Dumper\CsvFileDumper());
$a->addDumper('ini', new \Symfony\Component\Translation\Dumper\IniFileDumper());
$a->addDumper('json', new \Symfony\Component\Translation\Dumper\JsonFileDumper());
$a->addDumper('res', new \Symfony\Component\Translation\Dumper\IcuResFileDumper());

$this->privates['console.command.translation_update'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationUpdateCommand($a, ($this->privates['translation.reader'] ?? $this->load(__DIR__.'/getTranslation_ReaderService.php')), ($this->privates['translation.extractor'] ?? $this->load(__DIR__.'/getTranslation_ExtractorService.php')), 'en', ($this->targetDirs[3].'/translations'), ($this->targetDirs[3].'/templates'));

$instance->setName('translation:update');

return $instance;
