<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Type\TagsInputType' shared autowired service.

require_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
require_once $this->targetDirs[3].'/src/Form/Type/TagsInputType.php';

return $this->privates['App\Form\Type\TagsInputType'] = new \App\Form\Type\TagsInputType(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')));
